# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    name: Create Build
    if: "startsWith(github.event.head_commit.message, 'build: ')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: maven

      - name: Build
        run: mvn clean install

      - name: Upload Artifact
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: ${{ github.workspace }}/commons/target/*.jar, ${{ github.workspace }}/netsys-client/target/*.jar, ${{ github.workspace }}/netsys-server/target/*.jar
          draft: false
          name: NetSys Release
          tag: v1.1
          token: ${{ secrets.GITHUB_TOKEN }}
          body: "The artifacts are kept up to date with the branch release."
          commit: ${{ github.sha }}
          allowUpdates: true
          removeArtifacts: true
          replacesArtifacts: true